site_name: 2024 April All-Hands Meeting

theme:
  name: material
  palette:
    primary: white

docs_dir: ./docs

nav:
    - Home: index.md
    - Abstracts: ABSTRACTS.md
    - Code of Conduct: CODEOFCONDUCT.md
    - Contact: CONTACT.md
    - COVID-19 Precautions: COVID.md
    - Restaurants: RESTAURANTS.md
    - Video Recordings: VIDEOS.md
